name: Fetch Social Activities

on:
  # 30分ごとに自動実行
  schedule:
    - cron: '*/30 * * * *'
  # Actionsタブから手動で実行できるようにする
  workflow_dispatch:

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- ↓↓↓ ここからデバッグ用のステップを追加 ↓↓↓ ---
      - name: Debug Secrets Existence
        run: |
          if [ -n "$GIST_ID" ]; then echo "✅ GIST_ID is set."; else echo "❌ GIST_ID is NOT set."; fi
          if [ -n "$GIST_TOKEN" ]; then echo "✅ GIST_TOKEN is set."; else echo "❌ GIST_TOKEN is NOT set."; fi
          if [ -n "$YOUTUBE_API_KEY" ]; then echo "✅ YOUTUBE_API_KEY is set."; else echo "❌ YOUTUBE_API_KEY is NOT set."; fi
          if [ -n "$GH_API_TOKEN" ]; then echo "✅ GH_API_TOKEN is set."; else echo "❌ GH_API_TOKEN is NOT set."; fi
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
      # --- ↑↑↑ ここまでデバッグ用のステップを追加 ↑↑↑ ---

      - name: Install dependencies
        run: npm install

      - name: Run fetch script
        run: node scripts/fetch_activities.js
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

